### ISSUE TITLE
Non-deterministic test?

### ISSUE THREAD

**Issue by LukeMathWalker** [jturner314/ndarray-stats#6]
```rust
    #[test]
    fn test_zero_observations() {
        let a = Array2::<f32>::zeros((2, 0));
        let pearson = a.pearson_correlation();
        assert_eq!(pearson.shape(), &[2, 2]);
        let all_nan_flag = pearson.iter().map(|x| x.is_nan()).fold(true, |acc, flag| acc & flag);
        assert_eq!(all_nan_flag, true);
    }
```
This test fails on Travis, for #5, while it succeeds on my local machine.
It's weird - any idea? @jturner314 
I am trying to reproduce the error, but I am failing.

**Comment by LukeMathWalker** [comment]
On Travis CI the `pearson` matrix is:
```
[[-inf, inf],
 [inf, inf]]
```

**Comment by LukeMathWalker** [comment]
I have added a test to check that the covariance matrix with zero observations is indeed a matrix filled with zeroes and once again I get different results on Travis CI vs local machine:
```
test correlation::cov_tests::test_covariance_zero_observations ... FAILED
```

```rust
    #[test]
    fn test_covariance_zero_observations() {
        let a = Array2::<f32>::zeros((2, 0));
        // Negative ddof (-1 < 0) to avoid invalid-ddof panic
        let cov = a.cov(-1.);
        assert_eq!(cov.shape(), &[2, 2]);
        assert!(cov.all_close(&Array2::<f32>::zeros((2, 2)), 1e-8));
    }
```

**Comment by jturner314** [comment]
You've discovered a couple of bugs:

* It appears that `.dot()` of a 2 × 0 matrix and a 0 × 2 matrix [returns a 2 × 2 matrix of uninitialized memory](https://github.com/bluss/ndarray/blob/a175675fd7d600cf618b70262db591a3ccbc81e6/src/linalg/impl_linalg.rs#L266-L273), when it should return a 2 × 2 matrix of zeros.

* The `test_covariance_zero_observations` test I added in #4 is broken in a couple of ways: `cov.mapv(|x| x.is_nan())` doesn't do anything; it should have been `cov.mapv(|x| assert!(x.is_nan()))`. But, NaN values aren't correct in this case (compare to NumPy, which gives NaNs for `ddof = 0` and zeros for `ddof = -1`); it really should have been `cov.mapv(|x| assert_eq!(x, 0.))`, as you discovered.

I don't have time right now to fix these things, but I'll take a look later.

**Comment by jturner314** [comment]
I think #7 should fix the nondeterministic behavior you are observing.

> What should I expect from the component-wise division of two zero-filled matrices? NaN? Random infs?

You can see the behavior of floating point division by zero with this program:

```rust
fn main() {
    for a in &[-1., -0., 0., 1.] {
        for b in &[-0., 0.] {
            println!("{:?} / {:?} = {:?}", a, b, a / b);
        }
    }
}
```

The result is:

```
-1.0 / -0.0 = inf
-1.0 / 0.0 = -inf
-0.0 / -0.0 = NaN
-0.0 / 0.0 = NaN
0.0 / -0.0 = NaN
0.0 / 0.0 = NaN
1.0 / -0.0 = -inf
1.0 / 0.0 = inf
```

In other words, zero divided by zero is NaN, while non-zero divided by zero is ±inf (sign determined by both operands).

For the `shape = (2, 0)` case, the correlation coefficient should be a 2×2 array of NaNs. You can confirm this with NumPy:

```python
>>> import numpy as np
>>> np.corrcoef(np.zeros((2, 0)))
/usr/lib/python3.7/site-packages/numpy/lib/function_base.py:356: RuntimeWarning: Mean of empty slice.
  avg = a.mean(axis)
/usr/lib/python3.7/site-packages/numpy/core/_methods.py:78: RuntimeWarning: invalid value encountered in true_divide
  ret, rcount, out=ret, casting='unsafe', subok=False)
/usr/lib/python3.7/site-packages/numpy/lib/function_base.py:2392: RuntimeWarning: Degrees of freedom <= 0 for slice
  c = cov(x, y, rowvar)
/usr/lib/python3.7/site-packages/numpy/lib/function_base.py:2326: RuntimeWarning: divide by zero encountered in true_divide
  c *= np.true_divide(1, fact)
/usr/lib/python3.7/site-packages/numpy/lib/function_base.py:2326: RuntimeWarning: invalid value encountered in multiply
  c *= np.true_divide(1, fact)
array([[nan, nan],
       [nan, nan]])
```

**Comment by LukeMathWalker** [comment]
Great - thanks for the quick fix!
It turns out I was looking at the wrong dot function :stuck_out_tongue: 
I'll merge master back into my branch to finalize the PR then!
